"""AUTO-GENERATED by scripts/compute_bitcoin_monthly.py — do not edit by hand.

Generated: 2026-08-05T16:30:24Z
Verdict: partially | regime: mixed
"""

from __future__ import annotations

GENERATED_AT = '2026-08-05T16:30:24Z'
MIN_CELL_N = 3
BEAR_PHASE_DAYS = 364
BULL_PHASE_DAYS = 1064

# Calendar month average returns (BTC-USD), pct
BTC_CALENDAR_MONTHLY_RETURNS: dict[int, float] = {1: -1.15, 2: 10.19, 3: 0.48, 4: 10.16, 5: 8.08, 6: 0.05, 7: 8.88, 8: 0.1, 9: -1.82, 10: 16.63, 11: 7.51, 12: 7.14}

BTC_CALENDAR_MONTHLY_N: dict[int, int] = {1: 12, 2: 12, 3: 12, 4: 12, 5: 12, 6: 12, 7: 12, 8: 13, 9: 11, 10: 12, 11: 12, 12: 12}

# S&P 500 (^GSPC) same window — comparison only
SPX_CALENDAR_MONTHLY_RETURNS: dict[int, float] = {1: 1.28, 2: 0.87, 3: 0.48, 4: 1.67, 5: 0.54, 6: 0.74, 7: 2.65, 8: -0.08, 9: -0.66, 10: 2.13, 11: 2.9, 12: 0.55}

# ATH phase × calendar month; None = below MIN_CELL_N
BTC_PHASE_MONTHLY_RETURNS: dict[str, dict[int, float | None]] = {
    'bear_early': {1: -9.6, 2: 9.39, 3: -1.9, 4: 6.54, 5: 3.67, 6: 4.87, 7: 7.72, 8: 10.75, 9: -0.9, 10: 11.88, 11: 10.36, 12: 2.01},
    'bear_late': {1: None, 2: None, 3: None, 4: None, 5: 4.15, 6: -14.61, 7: 13.73, 8: -7.97, 9: -0.51, 10: 12.93, 11: None, 12: None},
    'bull_early': {1: 20.74, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None, 9: -2.42, 10: 24.19, 11: -1.27, 12: -0.84},
    'bull_mid': {1: None, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None, 9: None, 10: None, 11: None, 12: None},
    'late_distribution': {1: None, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None, 9: None, 10: None, 11: None, 12: None},
}

BTC_PHASE_MONTHLY_N: dict[str, dict[int, int]] = {
    'bear_early': {1: 8, 2: 8, 3: 8, 4: 7, 5: 6, 6: 5, 7: 5, 8: 5, 9: 4, 10: 4, 11: 5, 12: 6},
    'bear_late': {1: 0, 2: 0, 3: 0, 4: 2, 5: 3, 6: 4, 7: 4, 8: 5, 9: 3, 10: 4, 11: 2, 12: 1},
    'bull_early': {1: 3, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 3, 10: 3, 11: 4, 12: 4},
    'bull_mid': {1: 1, 2: 2, 3: 2, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1},
    'late_distribution': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0},
}

SPX_COMPARISON: dict = {
    "corr_full": 0.339,
    "corr_rolling_24m_latest": 0.43,
    "corr_rolling_24m_avg": 0.346,
    "best_six_btc_avg_pct": 5.72,
    "best_six_spx_avg_pct": 1.29,
    "worst_six_btc_avg_pct": 5.32,
    "worst_six_spx_avg_pct": 0.89,
    "best_six_delta_pct": 4.43,
    "month_sign_agreement": 10,
    "verdict": 'partially',
    "regime": 'mixed',
    "aligned_months": 144,
    "btc_term_year_avgs": {1: 9.21, 2: -4.76, 3: 7.32, 4: 10.37},
    "spx_term_year_avgs": {1: 1.56, 2: 0.58, 3: 0.79, 4: 1.47},
}
