#!/usr/bin/env bash
# Generuje klucz Cope Capital i zapisuje do .env (poza Dockerem).
# Użycie: ./scripts/fomo-register-key.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "→ Rejestracja u Cope Capital…"
RESP="$(curl -sS -X POST "https://api.cope.capital/v1/register" \
  -H "Content-Type: application/json" \
  -d '{"agent_name":"cyclical-trader-fomo-ghost","description":"Cyclical Trader FOMO Ghost top-30"}')" || {
  echo "✗ curl failed — sprawdź sieć / status api.cope.capital"
  exit 1
}

KEY="$(python3 - <<'PY' "$RESP"
import json,sys
raw=sys.argv[1]
try:
    data=json.loads(raw)
except json.JSONDecodeError:
    print("", end="")
    sys.exit(2)
print(str(data.get("api_key") or "").strip())
PY
)" || true

if [[ -z "${KEY}" || "${KEY}" != cope_* ]]; then
  echo "✗ Brak api_key w odpowiedzi Cope:"
  echo "$RESP" | head -c 500
  echo
  echo "Gdy API wróci, uruchom ten skrypt ponownie."
  exit 1
fi

ENV_FILE="$ROOT/.env"
LINE="CYCLICAL_COPE_API_KEY=${KEY}"
if [[ -f "$ENV_FILE" ]] && grep -q '^CYCLICAL_COPE_API_KEY=' "$ENV_FILE"; then
  # macOS / BSD sed
  if sed --version >/dev/null 2>&1; then
    sed -i "s|^CYCLICAL_COPE_API_KEY=.*|${LINE}|" "$ENV_FILE"
  else
    sed -i '' "s|^CYCLICAL_COPE_API_KEY=.*|${LINE}|" "$ENV_FILE"
  fi
else
  {
    echo ""
    echo "# FOMO Ghost (Cope Capital) — generated by scripts/fomo-register-key.sh"
    echo "$LINE"
  } >> "$ENV_FILE"
fi

mkdir -p "$ROOT/backend/data"
printf '%s\n' "$KEY" > "$ROOT/backend/data/cope_api_key.txt"
chmod 600 "$ROOT/backend/data/cope_api_key.txt" 2>/dev/null || true

echo "✓ Zapisano:"
echo "  .env → CYCLICAL_COPE_API_KEY=${KEY:0:14}…"
echo "  backend/data/cope_api_key.txt"
echo
echo "Uruchom lokalnie (poza Dockerem), np.:"
echo "  ./scripts/dev-up.sh"
echo "albo tylko backend z .env — potem otwórz http://127.0.0.1:8080/fomo"
